---
apiVersion: v1
kind: Secret
metadata:
  name: var-system-domain
type: Opaque
stringData:
  value: foo.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-deployment
    releases:
    - name: nats
      version: "33"
      url: ghcr.io/cloudfoundry-incubator
      stemcell:
        os: SLE_15_SP1
        version: 27.8-7.0.0_374.gb8e8e6af
    instance_groups:
    - name: nats
      instances: 1
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((nats_password))
            domain: ((system_domain))
    variables:
    - name: nats_password
      type: password
    - name: nats_ca
      type: certificate
      options:
        is_ca: true
        common_name: routerCA
    - name: nats_cert
      type: certificate
      options:
        ca: nats_ca
        common_name: routerSSL
        alternative_names:
        - "foo.bar"
        - "*.foo.bar"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
