---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-deployment
    releases:
    - name: nats
      version: "33"
      url: docker.io/cfcontainerization
      stemcell:
        os: SLE_15_SP1
        version: 26.1-7.0.0_374.gb8e8e6af
    instance_groups:
    - name: nats
      instances: 1
      env:
        bosh:
          agent:
            settings:
              preRenderOps:
                bpm:
                - type: replace
                  path: /configs/nats/processes/name=nats/env?
                  value:
                    FOO: deadbeef
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((nats_password))
          quarks:
            ports:
            - name: "nats"
              protocol: "TCP"
              internal: 4222
            - name: "nats-routes"
              protocol: TCP
              internal: 4223
    variables:
    - name: nats_password
      type: password
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
  ops: []
