---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarks-gora1-manifest
data:
  manifest: |
    ---
    name: quarks-gora1-deployment
    releases:
    - name: quarks-gora
      version: "0.0.7"
      url: docker.io/cfcontainerization
      stemcell:
        os: SLE_15_SP1-26.5
        version: 7.0.0_374.gb8e8e6af
    instance_groups:
    - name: quarks-gora1
      instances: 1
      jobs:
      - name: quarks-gora
        release: quarks-gora
        properties:
          quarks-gora:
            port: 55556
            cert: ((quarks_gora_ssl/certificate))
            key: ((quarks_gora_ssl/private_key))
          quarks:
            ports:
            - name: "quarks-gora"
              protocol: "TCP"
              internal: 55556
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: quarks-gora1-deployment
spec:
  manifest:
    name: quarks-gora1-manifest
    type: configmap
  ops:
  - name: ops-scale2
    type: configmap
