apiVersion: v1
kind: ConfigMap
metadata:
  name: quarks-gora-manifest
data:
  manifest: |
    ---
    name: quarks-gora-deployment
    releases:
    - name: quarks-gora
      version: "0.0.17"
      url: ghcr.io/cloudfoundry-incubator
      stemcell:
        os: SLE_15_SP2
        version: 29.6-7.0.0_374.gb8e8e6af
    instance_groups:
    - name: quarks-gora
      instances: 1
      env:
        bosh:
          agent:
            settings:
              terminationGracePeriodSeconds: 70
      jobs:
      - name: loop-drain-job
        release: quarks-gora
      - name: quarks-gora
        release: quarks-gora
        properties:
          quarks-gora:
            port: 55556
            ssl: false
          quarks:
            ports:
            - name: "quarks-gora"
              protocol: "TCP"
              internal: 55556
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: quarks-gora-deployment
spec:
  manifest:
    name: quarks-gora-manifest
    type: configmap
