---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-scale
data:
  ops: |
    - type: replace
      path: /instance_groups/name=quarks-gora?/instances
      value: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarks-gora-manifest
data:
  manifest: |
    ---
    name: quarks-gora-deployment
    releases:
    - name: quarks-gora
      version: "0.0.15"
      url: ghcr.io/cloudfoundry-incubator
      stemcell:
        os: SLE_15_SP1
        version: 27.10-7.0.0_374.gb8e8e6af
    instance_groups:
    - name: quarks-gora
      instances: 1
      jobs:
      - name: quarks-gora
        release: quarks-gora
        properties:
          quarks-gora:
            port: 55556
            ssl: false
          quarks:
            ports:
            - name: "quarks-gora"
              protocol: "TCP"
              internal: 55556
            bpm:
              processes:
              - name: quarks-gora
                requests:
                  cpu: "2m"
                  memory: "128Mi"
                limits:
                  cpu: "4"
                  memory: "2Gi"
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: quarks-gora-deployment
spec:
  manifest:
    name: quarks-gora-manifest
    type: configmap
  ops:
  - name: ops-scale
    type: configmap
