version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  ignore:
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
  - dependency-name: github.com/spf13/afero
    versions:
    - 1.5.1
  - dependency-name: github.com/gonvenience/bunt
    versions:
    - 1.2.0
    - 1.3.0
    - 1.3.1
