apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: cfcontainerization/cf-operator
    context: .
    custom:
      buildCommand: bin/build-image
      dependencies: {}
  local:
    push: false
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: cf-operator
      chartPath: deploy/helm/cf-operator
      setValueTemplates:
        image.tag: "{{ .DIGEST }}"
        env.CF_OPERATOR_NAMESPACE: "{{ .CF_OPERATOR_NAMESPACE }}"
      wait: true
