---
apiVersion: v1
kind: Secret
metadata:
  labels:
    quarks.cloudfoundry.org/secret-kind: generated
  annotations:
    quarks.cloudfoundry.org/secret-copy-of: NAMESPACE/generate-password-with-copies
  name: copied-secret
  namespace: COPYNAMESPACE
