{{- if .Values.global.rbacEnable }}
---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: {{ template "cf-operator.fullname" . }}
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: {{ template "cf-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
    roleRef:
      kind: ClusterRole
      name: {{ template "cf-operator.fullname" . }}
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: {{ template "cf-operator.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}
