apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cf-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.image.credentials }}
imagePullSecrets:
- name: {{ template "cf-operator.serviceAccountName" . }}-pull-secret
{{- end }}
