apiVersion: v1
kind: Service
metadata:
  name: cf-operator-webhook
spec:
  {{- if or .Values.global.operator.webhook.useServiceReference (not .Values.operator.webhook.endpoint) }}
  selector:
    name: cf-operator
  {{- end }}
  ports:
  - port: 443
    targetPort: 2999
