apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: ExtendedStatefulSet
metadata:
  name: example-extendedstatefulset
spec:
  template:
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: example-statefulset
      template:
        metadata:
          labels:
            app: example-statefulset
        spec:
          containers:
          - name: busybox
            image: busybox
            command:
            - sleep
            - "3600"
