---
apiVersion: v1
kind: Secret
metadata:
  name: cf-operator-testing-manifest
stringData:
  manifest: |
    ---
    releases:
    - name: quarks-gora
      version: "0.0.15"
      url: ghcr.io/cloudfoundry-incubator
      stemcell:
        os: SLE_15_SP1
        version: 27.10-7.0.0_374.gb8e8e6af
    instance_groups:
    - name: quarks-gora
      instances: 2
      lifecycle: errand
      jobs:
      - name: smoke-tests
        release: quarks-gora
        consumes:
          quarks-gora: {from: quarks-gora}
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: cfo-test-deployment
spec:
  manifest:
    name: cf-operator-testing-manifest
    type: secret
