apiVersion: v1
kind: Secret
metadata:
  name: somesecret
  labels:
    quarks.cloudfoundry.org/deployment-name: "cfo-test-deployment"
  annotations:
    quarks.cloudfoundry.org/provides: '{"name":"quarks-gora","type":"quarks-gora"}'
stringData:
  link: |
    quarks-gora.ssl: false
    quarks-gora.port: "1234"
    text_message: admin
