---
apiVersion: v1
kind: Service
metadata:
  labels:
    quarks.cloudfoundry.org/deployment-name: "cfo-test-deployment"
  annotations:
    quarks.cloudfoundry.org/link-provider-name: quarks-gora
  name: endpointsvc
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: client
---
apiVersion: v1
kind: Endpoints
metadata:
  name: endpointsvc
subsets:
  - addresses:
      - ip: 192.1.2.34
    ports:
      - port: 1234
