apiVersion: v1
kind: Service
metadata:
  labels:
    quarks.cloudfoundry.org/deployment-name: "cfo-test-deployment"
  annotations:
    quarks.cloudfoundry.org/link-provider-name: quarks-gora
  name: svcexternal
spec:
  type: ExternalName
  externalName: test.example.com
