---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: extendedsecrets.quarks.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: quarks.cloudfoundry.org
  names:
    kind: ExtendedSecret
    listKind: ExtendedSecretList
    plural: extendedsecrets
    singular: extendedsecret
    shortNames:
        - esec
        - esecs
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
