apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksStatefulSet
metadata:
  name: example-quarks-statefulset
spec:
  template:
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: example-statefulset
      template:
        metadata:
          labels:
            app: example-statefulset
        spec:
          containers:
          - name: busybox
            image: busybox
            command:
            - sleep
            - "3600"
            volumeMounts:
              - name: pvc
                mountPath: "/etc/volume"
      volumeClaimTemplates:
      - metadata:
          name: pvc
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
