# Default values for cf-operator.
image:
  repository: cf-operator
  org: cfcontainerization
  tag: foobar

operator:
  webhook:
    endpoint: ~
    host: ~
    port: "2999"
    useServiceReference: true

cluster:
  domain: ~

nameOverride: ""

fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  cfOperatorServiceAccount:
    create: true
    name:

global:
  contextTimeout: 30
  image:
    pullPolicy: IfNotPresent
    credentials: ~
  operator:
    watchNamespace: ""
  rbacEnable: true

quarks-job:
  createWatchNamespace: false
  serviceAccount:
    quarksJobServiceAccount:
      create: true
      name:
