# Default values for cf-operator.
image:
  repository: cf-operator
  org: cfcontainerization
  tag: foobar
  pullPolicy: IfNotPresent

operator:
  watchNamespace: ""
  webhook:
    host: ~
    port: "2999"
    useServiceReference: false

cluster:
  domain: ~

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

rbacEnable: true

serviceAccount:
  cfOperatorServiceAccount:
    create: true
    name:
