# Default values for cf-operator.
image:
  repository: cfcontainerization/cf-operator
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

operator:
  webhook:
    port: 2999
